service: whiskers-2
frameworkVersion: '2 || 3'

plugins:
  - serverless-offline
custom:
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  lambda-handler:
    handler: dist/index.handler
    events:
      - http:
          path: /{any+}
          method: any
