
name: Deploy Dev
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Serverless AWS authentication
      run: yarn sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_KEY }}
    - name: Deploy Lambda functions
      run: yarn deploy:prod
